### ISSUE TITLE
USER STORY: Inzien van documenten bij zaken

### ISSUE THREAD

**Issue by robwagelaar** [Dimpact-Samenwerking/PodiumD#164]
Als inwoner wil ik in OIP documenten die bij mijn zaak horen kunnen inzien/downloaden zodat ik direct over de juiste informatie beschik

Acceptatiecriteria:

- Alleen documenten tonen indien status Definitief is en documentrichting Extern is (eSuite)
- Alleen documenten tonen in indien vertouwelijkheidaanduiding gelijk is aan.... NTB (OpenZaak)`

#36

**Comment by Snijhuis** [comment]
- Documenten tonen bij zaken uit e-Suite:
  - Documentstatus 'Definitief' + documentrichting 'Extern'. Status lijkt wel mee te komen, richting niet. Andy checkt dit (Atos)
  - Publicatieniveau documenten uit e-Suite = gemapt op Vertrouwelijkheidsaanduiding in ZGW Api. Extern= Openbaar. Alleen openbaar tonen in OIP
  - Document downloaden wordt opgepakt door Maykin (informatieobject API van e-Suite bekijken)

**Comment by robwagelaar** [comment]
Loopt al bij Maykin (Sprint 9) voor OIP.

**Comment by robwagelaar** [comment]
Gerealiseerd in sprint 9 van OIP.
