### ISSUE TITLE
EPIC: Handmatig starten van zaak doormiddel van een intern formulier (voor medewerkers)

### ISSUE THREAD

**Issue by Snijhuis** [Dimpact-Samenwerking/PodiumD#171]
***Als*** Zaakbehandelaar

***Wil ik*** Handmatig een zaak kunnen starten doormiddel van een intern formulier

***Zodat*** Ik net als **EN** namens een burger/ een bedrijf een zaak kan indienen en gedwongen wordt bepaalde vereiste informatie voor de zaakbehandeling te vullen

Acceptatiecriteria:
- Persoon of bedrijf (initiator) moet eerst geselecteerd kunnen worden door de medewerker uit de basisregistratie (HaalCentraal)
- Na keuze van zaaktype wordt een intern formulier gestart voor de medewerker (Embedded/ iFrame/ ?)
- Zaak van zaaktype wordt geregistreerd met bijbehorend document en gekoppeld aan de initiator
- Moet in te richten zijn dat een zaaktype een intern startformulier heeft. Wellicht te koppelen aan het communicatiekanaal? OF in te stellen bij Zaakstartparameters in ZAC? (link naar het interne formulier vullen oid). Opties moeten zijn: verplicht, optioneel, geen intern formulier starten.

Aanvullende vragen/opties (nader bepalen).
- De benodigde/aangeleverde informatie uit het formulier ook als velden beschikbaar komt in de behandeling van de zaak.
- Moet zowel voor e-Suite zaaktypen als OpenZaak/ZAC zaaktypen in te richten zijn

Vanuit ZAC reeds besproken (https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/310)
Oplossingsrichting bespreken in platform team

**Comment by PaskalKiers** [comment]
NL-AMS-LOCGOV/zaakafhandelcomponent#310 is een mogelijke MVP voor alle medewerkers.  
Voor het eindplaatje vind ik dit vooral een logische keuze voor  behandelaren die in de ZAC zitten werken.  Al vraag ik me af of het in de rol van behandelaar is dat ze het aanmaken, eerder in de rol van klantcontacter. 
Voor telefonisten (de overduidelijke klantcontacters) vind ik KISS (onderdeel van PodiumD toch) een veel logischer plek om het startformulier aan te bieden voor een zaaktype, al dan niet met gebruik van OF.  Anders moeten ze naast hun eigen klantcontactsysteem weer inloggen in het zaaksysteem, terwijl de kracht van CG is dat je daar efficienter mee om kunt gaan. 
Dit is de omnichannelgedachte denk ik

**Comment by Snijhuis** [comment]
Opgenomen in JIRA: Intern formulier niet als oplossingsrichting benoemd. Wel de benodigde functionaliteit.
Zie https://dimpact.atlassian.net/browse/POD-87
