### ISSUE TITLE
EPIC: E-Suite als consumer van Open Zaak

### ISSUE THREAD

**Issue by Snijhuis** [Dimpact-Samenwerking/PodiumD#79]
***Als*** Gemeente

***Wil ik*** dat de e-Suite zaken en documenten registreert in Open Zaak

***Zodat*** ik vanuit Open Zaak mijn Archiefwerkzaamheden zou kunnen doen (Via ntb apps) en zaken in mijn loket kan tonen

NB. Specifieke stories nog uitwerken
- Voor achriefwerkzaamheden
- Voor mijn loket

Prio WG Implementatie: Hoog

**Comment by Snijhuis** [comment]
#6

**Comment by Hugo-ter-Doest** [comment]
duplicaat van #75

**Comment by Snijhuis** [comment]
@Hugo-ter-Doest Duplicaat gesloten. Deze epic algemeen gemaakt, specifieke stories uitwerken om goed de uren in te schatten

**Comment by Snijhuis** [comment]
Met Hugo bespreken

**Comment by Snijhuis** [comment]
@Hugo-ter-Doest Deze route in de transitie pakken we (nog) niet op. Ik sluit hier de EPIC. Indien nodig graag een nieuwe epic maken in JIRA
