### ISSUE TITLE
USER STORY: Ophalen productaanvraag door e-Suite

### ISSUE THREAD

**Issue by PaskalKiers** [Dimpact-Samenwerking/PodiumD#88]
Behorend bij #71 

***Als*** gemeente 
***wil ik*** dat de e-Suite productaanvraaginformatie kan ophalen op basis van ontvangen data
***zodat*** de e-Suite de informatie heeft om een zaak te starten voor de initiator. 

Acceptatiecriteria:
•	De productaanvraag is gerelateerd aan het referentienummer dat in Open Formuleren is teruggekoppeld aan de initiator.

**Comment by Snijhuis** [comment]
Opgevoerd in Jira https://support.dimpact.nl/jira/browse/WIJZ-645

**Comment by StefSchots1993** [comment]
Opgevoerd in ATOS JIRA - https://crjira.fsc.atos-services.net/browse/ESUITEXT-11892

**Comment by PaskalKiers** [comment]
Gerealiseerd in 4.32, maar data in productaanvraag is onvoldoende
