### ISSUE TITLE
USER STORY: Aanmaken zaak in e-Suite op basis van productaanvraaginformatie

### ISSUE THREAD

**Issue by PaskalKiers** [Dimpact-Samenwerking/PodiumD#89]
Behorend bij #71 
***Als*** gemeente 
***wil ik***dat de e-Suite een zaak aan kan maken op basis van de opgehaalde productaanvraaginformatie 
***zodat*** ik Open formulieren kan gebruiken om aanvraaginformatie (van burgers) te verzamelen.

Acceptatiecriteria:
•	De aanvrager heeft één nummer teruggekoppeld gekregen, op basis waarvan hij/zij de zaak kan volgen.
**•	De resulterende zaak is te behandelen via het bestaande e-Suite proces (op basis van het zaaktype)**
•	De documenten zijn benaderbaar vanuit de zaak
•	De rollen zijn gekoppeld aan de zaak
•	De zaak is toegewezen aan de ingestelde groep / behandelaar.
•	De zaak is vindbaar door de servicedesk onder het referentienummer dat teruggekoppeld is aan de indiener.
•	De zaak is vindbaar door de indiener in de loketfunctionaliteit onder het referentienummer dat teruggekoppeld is aan de indiener. (waarschijnlijk loketstory voor Rotterdam)
•	De gegevens uit de productaanvraag zijn beschikbaar in de zaaktaken (mits ze aangeroepen worden in de taak).

**Comment by Snijhuis** [comment]
Opgevoerd in Jira https://support.dimpact.nl/jira/browse/WIJZ-646

**Comment by StefSchots1993** [comment]
Opgevoerd in ATOS JIRA - https://crjira.fsc.atos-services.net/browse/ESUITEXT-11893

**Comment by PaskalKiers** [comment]
• De resulterende zaak is te behandelen via het bestaande e-Suite proces (op basis van het zaaktype)  --> epic #105 en #182
• De rollen zijn gekoppeld aan de zaak--> aparte stories in eerste instantie Digid en eherkenning

**Comment by PaskalKiers** [comment]
In Dimpact-Jira is de ticket gesloten, maar in ieder geval het belangrijkste acceptatiecriterium is niet gehaald.

**Comment by StefSchots1993** [comment]
@PaskalKiers - In je mail van gisteren zeg je dat deze gesloten is en restpunten via https://github.com/Dimpact-Samenwerking/PodiumD/issues/203 opgepakt worden. Volgens mij kan deze dan dus dicht toch?

**Comment by PaskalKiers** [comment]
Ja, dacht dat ik dat al gedaan had. :)
